### ISSUE TITLE
Accepting cancellation token results into a generated code that has build issues

### ISSUE THREAD

**Issue by yasmoradi** [surgicalcoder/ApiClientGenerator#6]
Accepting cancellation token at server side is really important, and some strange things happen If I accept cancellation token in my api controllers.

```csharp
[HttpGet]
public async Task<SomeDto[]> GetAll(CancellationToken cancellationToken)
{
    throw new NotImplementedException();
}
```
It generates the followings:
![image](https://github.com/surgicalcoder/ApiClientGenerator/assets/5352980/2b517953-9854-48cc-8f63-8be8e8b95367)
instead of the followings:
```csharp
public async Task<SomeDto[]?> GetAll(CancellationToken _token = default)
{
    using var result = await _client.GetAsync($"/api/Problesm/GetAll/", cancellationToken: _token);
    return await result.Content?.ReadFromJsonAsync<SomeDto[]>(cancellationToken: _token);
}
```
Thanks to the web api value providers, the list of strange things that people can accept in their api actions is unlimited!
For example we [accept](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/BlazorWeb/Bit.BlazorWeb/src/BlazorWeb.Server/Controllers/Categories/CategoryController.cs#L29) `ODataQueryOptions<SomeDto>` which gets filled by web api.
I'm not asking you to ignore all of them in your code, but it would be a good idea to accept a list of parameter types in `ApiClientGenerator.json` file, so parameters with those types will be ignored in generated code.

**Comment by surgicalcoder** [comment]
@ysmoradi the cancellation token isn't a problem - how do you see the json work? If the type is mentioned in there, then when generating the client, we ignore the parameter as if it didn't exist?

**Comment by yasmoradi** [comment]
Exactly! Yes, I know `CancellationToken` is ignored explicitly, but there is a long list of other types to be ignored, that's why making that configurable does make sense!

**Comment by surgicalcoder** [comment]
Hi @ysmoradi I've done some work in v2.5.0 - the  [settings](https://github.com/surgicalcoder/ApiClientGenerator/blob/master/GoLive.Generator.ApiClientGenerator.Tests.WebApi/ApiClientGenerator.json) example gives you an idea - you can ignore by type, by generic type (ie. any List<T>), or anything that has a certain attribute.

I've also implemented using IModelNameProvider.Name for renaming properties, and while I was at it, you can also set up rules to change types of parameters that get's outputted.

Hopefully this meets your requirements :)
