### ISSUE TITLE
Method comments are not copied to the generated code

### ISSUE THREAD

**Issue by yasmoradi** [surgicalcoder/ApiClientGenerator#8]
It would be so helpful if we copy xml comments of the code as is to the generated method.
So, for the followings:
```csharp
/// <summary>
/// It doesn't copy this summary to the generated code
/// </summary>
[HttpPost]
public async Task CommentIssue()
{
}
```
We could have something like this:
```csharp
/// <summary>
/// It doesn't copy this summary to the generated code
/// </summary>
public async Task<Task?> CommentIssue(CancellationToken _token = default)
{
    using var result = await _client.PostAsJsonAsync($"/api/Problesm/CommentIssue/", new {}, cancellationToken: _token);
    return await result.Content?.ReadFromJsonAsync<Task>(cancellationToken: _token);
}
```
For some reason, this is return `Task<Task>` which is not making any sense.

**Comment by surgicalcoder** [comment]
@ysmoradi This will take longer to implement, it's tricker than I thought - it will get done, just working the other issues you've raised sofar first :)

**Comment by surgicalcoder** [comment]
@ysmoradi This is fixed with v3 :smile:  Enjoy!
